### PR TITLE
Remove Broken embed

### PR DESCRIPTION
**Pull request by xcfio**
### Description
Remove broken YouTube link from pages/scams/refund.mdx

- [ ] Adding new page
- [ ] Updating existing documentation
- [x] Other updates

### CODE REVIEW

**Comment by Wuemeli** [comment]
@NoTextToSpeech

**Comment by totallytavi** [comment]
Checked the page myself just now. The video embeds fine.

**Comment by xcfio** [comment]
> Checked the page myself just now. The video embeds fine.

Maybe the video owner made it private and has now made it public.

**Comment by xcfio** [comment]
> Checked the page myself just now. The video embeds fine.

Maybe the video owner made it private and has now made it public.

**Pull request closed without merging**
